import NavBar from '@/components/molecules/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='wrapper'>
          <NavBar/>
          {children}
          </div></body>
    </html>
  )
}
