import Header from "../../components/Layouts/Header";
import "./globals.css";

export const metadata = {
    title: "Thaw",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-white">
                <Header />
                <div className="mx-auto w-[1440px] h-full">{children}</div>
            </body>
        </html>
    );
}
